databases:
  - name: orion_pg
    databaseName: orion_production
    user: orion
    region: oregon
services:
  - type: redis
    name: orion-sidekiq-redis
    region: oregon
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections
  - type: redis
    name: orion-actioncable-redis
    region: oregon
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections
  - type: web
    name: orion
    env: ruby
    region: oregon
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: APPLICATION_HOST
        sync: false
      - key: ASSET_HOST
        sync: false
      - key: SMTP_ADDRESS
        sync: false
      - key: SMTP_DOMAIN
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: orion_pg
          property: connectionString
      - key: RAILS_MASTER_KEY
        generateValue: false
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: false
        sync: false
      - key: RACK_ENV
        value: production
        sync: false
      - key: SIDEKIQ_USERNAME
        value: sidekiq
      - key: SIDEKIQ_PASSWORD
        sync: false
      - key: ACTIONCABLE_REDIS_URL
        fromService:
          type: redis
          name: orion-actioncable-redis
          property: connectionString
  - type: worker
    name: orion-sidekiq-worker
    env: ruby
    region: oregon
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -C ./config/sidekiq.yml
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: orion_pg
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: orion-sidekiq-redis
          property: connectionString