# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: true
:concurrency: 5
:timeout: 25

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - ["default", 5]
  - ["mailers", 1]

# # you can override concurrency based on environment
# production:
#   :concurrency: 25
# staging:
#   :concurrency: 25